apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: kube-alive
  name: cpuhog-deployment
  labels:
    app: cpuhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpuhog
  template:
    metadata:
      labels:
        app: cpuhog
    spec:
      containers:
      - name: cpuhog
        image: %%KUBEALIVE_DOCKER_REPO%%/cpuhog%%BRANCH_SUFFIX%%%%ARCHSUFFIX%%
        resources:
          requests:
            cpu: "0.25"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  namespace: kube-alive
  name: cpuhog
spec:
  selector:
    app: cpuhog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: kube-alive
  name: cpuhog-hpa
  labels:
    app: cpuhog
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: cpuhog-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
